- Updated to goreleaser v0.110.0. - Temporary fix for installing the provider from dist. - Always building before release.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -21,10 +21,18 @@ function log() {
 install_plugin() {
   local destination_dir="${1:?'A destination directory is required'}"
   log DEB "Installing plugin (src=${dist_dir:?} dest=${destination_dir:?})"
-  [[ ! -d "${dist_dir:?}" ]] && log ERR "Source directory not found (${dist_dir:?})" && exit 1
+  [[ ! -d "${dist_dir:?}" ]] && log ERR "Source directory not found (${dist_dir:?})! Please run build and try again..." && exit 1
   rm -rf "${destination_dir:?}/${plugins_dir:?}" &>/dev/null || true
   mkdir -p "${destination_dir:?}/${plugins_dir:?}" &>/dev/null || true
   cp -R "${dist_dir:?}/." "${destination_dir:?}/${plugins_dir:?}"
+
+  # Temporary fix. Issue: https://github.com/goreleaser/goreleaser/issues/1059
+  local dir_name
+  for dir in ${destination_dir:?}/${plugins_dir:?}/*/; do
+    dir_name="$(basename "${dir:?}")"
+    dir_name="${dir_name/dist_/}"
+    mv "${dir}" "${destination_dir:?}/${plugins_dir:?}/${dir_name:?}"
+  done
 }
 
 run_help() {
@@ -45,6 +53,7 @@ run_build() {
 }
 
 run_release() {
+  run_build
   run_test
   run_test_integration
 
